export const WsCode = {
    login: 'auth/login',
    logout: 'auth/logout',
    register: 'register',
    valid: "auth/valid",
    getConversation: 'chat/conversation',
    getProfile: 'users',
    getPost: "posts",
    getPostTimeLine: "posts/timeline",
    getListFriend: "users/friends",
    getConversation: "conversations",
    getAllMessageOfConversation: "messages",
    savePost: "posts",
    upload: "upload",
    searchFriend: "users/search",
    searchCov: 'conversations/find',
    updateConversation: "conversations/update",
    deleteImage: 'upload/delete',
    follow: 'users',
    register: 'auth/register',
    updateConversation: 'conversations/update/property',
    update_profile: 'users/update/profile',
    listInvite: 'users/list/invite',
}